apiVersion: apps/v1
kind: Deployment
metadata:
  name: palashnehalbhaishah
  labels:
    app: newapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: mynode
        image: palash315/task5.1p:latest
        ports:
        - containerPort: 8080